version: '3'
networks: 
  nvmanh-network:
    external: true
services:
  bida69:
    image: bida69_dev
    container_name: bida69_container_dev
    restart: always
    networks:
      - nvmanh-network
    ports:
      - '9009:443'   
    build:
      context: .
      dockerfile: MSOFT.bida69.core/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
